### ISSUE TITLE
デプロイ、定期実行、外部サービス呼び出しなど

### ISSUE THREAD

**Issue by mogamin** [enterprisegeeks/coolpoco#16]
※Serverlessの場合制約が多いので一緒に考える

いまは、もう
CloudFunctionでやることがなっている。
タスクの内容を再整理する

**Comment by taikichi225** [comment]
それぞれ以下の理由から本イシューをクローズとする。

【デプロイ】
#56 デプロイ方法を検証するに移行。

【定期実行】
定期実行は行わない。行うとしても、Clouderではなく、ServiceControllerで検討する。

【外部サービス呼び出し】
Clouderではなく、ServiceControllerで検討する。
