### ISSUE TITLE
Raspiの排熱状況をCPU温度から確認する

### ISSUE THREAD

**Issue by mogamin** [enterprisegeeks/coolpoco#39]

**Comment by ys-ryo** [comment]
排熱状況を確認するだけでは、安全面、消防面で問題ないことを保証できない。
業務用のラズパイを使用するなど、安全だと言えるものを購入することで対策する方針で検討する。

**Comment by ys-ryo** [comment]
産業用ラズベリーパイは4万円前後かかるため高価。Raspberry Pi3自体で安全だと言える根拠、方法がないか調査を行っています。

▼参考
RaspberryPiを産業用途に - BH3 | 株式会社ビズライト・テクノロジー
http://bh.bizright.co.jp/
産業用ラズベリーパイ
https://www.amazon.co.jp/産業用ラズベリーパイ-REVOLUTION-RevPi-Core3%EF%BC%88BCM2837-クアッドコア-eMMC%EF%BC%89/dp/B07571S3LG/ref=sr_1_1?hvadid=315596413400&hvdev=c&jp-ad-ap=0&keywords=%E7%94%A3%E6%A5%AD%E7%94%A8+%E3%83%A9%E3%82%BA%E3%83%99%E3%83%AA%E3%83%BC%E3%83%91%E3%82%A4&qid=1555904425&s=gateway&sr=8-1

**Comment by ys-ryo** [comment]
Raspberry Pi 3B+はPSEマークの取得はしていないが、PSEマーク取得要件である、J60950（国内規格）が準拠する「IEC 60950-1 2ND EDITION（定格電圧が600V以下の情報技術装置の安全性に関する国際規格）」に関しては認証済み。

▼参考
・Rasberry Pi 3B+が準拠している規格一覧
https://www.raspberrypi.org/documentation/hardware/raspberrypi/conformity.md
・「J60950(H16) 情報技術機器の安全性」
https://www.meti.go.jp/policy/consumer/seian/denan/hourei/gijutsukijun/040226-040227_revise/2kou/besshi_163.pdf
・IEC-J60950-1(情報機器)について
http://koukusu.com/japan/j_stand/iecj609501/j_stand_609501_const.html

**Comment by mogamin** [comment]
制限付きで配布するということにする。
