### ISSUE TITLE
Wifi/Bluetoothに接続したこと、接続していることがわかる方法

### ISSUE THREAD

**Issue by mogamin** [enterprisegeeks/coolpoco#40]

**Comment by takatakata** [comment]
# WiFi
- /var/log/syslog に接続・切断が記録される。1週間くらいログを蓄積して活用できそうか検討する。
- 【ログベースの場合】EventHandler側で、Fluentdでsyslogを抽出→フィルタ→イベント状態検知→IoT Core送信という流れを想定
- 【定期状態チェックの場合】SNMPコマンドで対象機器を定期死活チェック→イベント状態検知→IoT Core送信という流れを想定

# Bluetooth
- BlueZの診断系コマンドで対象機器を定期死活チェック→イベント状態検知→IoT Core送信という流れを想定

**Comment by mogamin** [comment]
* wifiはSNMPで診断する方向で。
* bluetoothも同じく診断系の方向で。

**Comment by takatakata** [comment]
hostapd（無線LANアクセスポイントDaemon）にSNMP CLIツールが付属しています。
「all_sta」引数で取得した全MIB変数に無線LANアクセスポイントにぶら下がっているクライアントが含まれています。その中からMACアドレスに該当するパターンを抽出します。
```bash
$ sudo hostapd_cli all_sta | grep "^\\w\\w:.*"
87:1a:31:fd:12:3c
f9:c2:31:49:2c:6f
```
